apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: gke-training
  labels:
    role: app
spec:
  replicas: 3 # 起動するコンテナ数
  selector:
    matchLabels:
      role: app
  template:
    metadata:
      labels:
        role: app
    spec:
      containers:
      - name: gke-training
        image: gcr.io/${PROJECT_ID}/gke-training:v${APP_VERSION} # コンテナのURL
        resources:
          requests:
            cpu: 100m # CPUを0.1コア確保
            memory: 64Mi # メモリ100MiB確保
        ports:
        - containerPort: 1323 # コンテナポートの指定
